language: java
install: true

jdk:
  - oraclejdk8
  
before_install:
  - chmod +x gradlew
  - ./gradlew dependencies || true  
  
script:
  - ./gradlew build -s
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=avsharapov-github -Dsonar.login=${SONAR_TOKEN}
 